# ...existing code...
class CalibrateFrame:
    # ...existing code...
    def detect_chessboard(self):
        # ...existing code to detect chessboard...
        if not chessboard_found:
            # 修改后的错误信息，确保文件命名一致
            corrected_path = self.file_path.replace("camera_ff", "camera_FF")
            raise Exception("The chessboard cannot be detected in this frame: " + corrected_path)
        # ...existing code...
